### Create User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "admin@teste.com.br",
  "password": "admin",
  "admin": true
}

### Sign-in User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "admin@teste.com.br",
  "password": "admin"
}

### Get current user
GET http://localhost:3000/auth/currentUser

###  Sign out
POST http://localhost:3000/auth/signout

###  Get all Users
GET http://localhost:3000/auth

###  Get all Users by email
GET http://localhost:3000/auth?email=2222222@teste.com.br

###  Get User by Id
GET http://localhost:3000/auth/11

### Delete User By Id
DELETE http://localhost:3000/auth/6

### Update User 
PATCH http://localhost:3000/auth/7
Content-Type: application/json

{
  "email": "patch@teste.com.br"
}